### ISSUE TITLE
[contrib] temporary supplemental style sheet (dark theme)

### ISSUE THREAD

**Issue by atomGit** [zakius/Smart-RSS#65]
NOTE that v2.10.0 of Smart RSS adds support for themes so this style sheet may not be needed

here's a rudimentary dark theme for Smart RSS if anyone is interested...

<details>
  <summary>v1.6 - click me</summary>

```css
/*
 * title: Smart RSS Reader, Darkness
 * version: 1.6
 * author: atomGit
 * comment: dark theme, easier on the eyes
 * install: save as '/chrome/smart.rss' - in 'userContent.css', add: @import "./custom/addon/smartrss.css";
 */

/*
 * Smart RSS chrome
 */
@-moz-document url("moz-extension://47f9cd7b-9fa3-4f66-9067-0c0c6a1b6264/rss.html") {
    .toolbar {
        background: #64ce81 !important;
    }
    input[type="search"] {
        background: #2c2c2c !important;
        color: #d8d8d8 !important;
        border: none !important;
    }
    .context-menu {
        background: black !important;
    }
    .context-menu-item:hover {
        color: black;
    }
    body {
        background: #202020 !important;
        color: #d8d8d8 !important;
    }
    .has-unread > .source-counter {
        color: black !important;
        background: #64ce81 !important;
    }
    .date-group {
        background: black !important;
    }
    .item-title {
        white-space: normal !important;
        overflow: visible !important;
        text-overflow: unset !important;
    }
    .unvisited, .unvisited .articles-list-item-author {
        color: #64ce81 !important;
    }
    .item-author {
        color: #8e8e8e !important;
    }
    .item-date {
        color: #8e8e8e !important;
    }
    h1 {
        color: unset !important;
        font-size: 1rem !important;
        max-height: unset !important;
        overflow: visible !important;
        text-overflow: unset !important;
    }
    .selected {
        background: #445f70 !important;
    }
    header .author {
        color: #b1b1b1 !important;
    }
    header .date {
        color: #b1b1b1 !important;
    }
    #indicator-progress {
    background: black !important;
    }
    #indicator-stop {
    background-color: red !important;
    }
    #properties {
    background: black !important;
    }
    #properties input, #properties select {
    background: #64ce81 !important;
    }
    
}

/*
 * Smart RSS feed content
 */
@-moz-document url("moz-extension://47f9cd7b-9fa3-4f66-9067-0c0c6a1b6264/rss_content.html") {
    body {
        font-family: sans-serif !important;
    }
    #smart-rss-content {
    color: #d8d8d8 !important;
    }
    a {
        color: #64ce81 !important;
    }
    footer a {
        background: #64ce81 !important;
        color: black !important;
        padding: 5px !important;
        border-radius: 4px !important;
    }
}
```
</details>

**Comment by asorel1942** [comment]
How could I add this to my copy of the extension?

**Comment by zakius** [comment]
currently it's only possible to use FF built in custom styling, it's not exactly user friendly and if I'm not mistaken it's now disabled by default

type about:support in address bar, click `open profile`, create `chrome` directory if it doesn't exist yet, create file named `userContent.css` and you actually can just paste everything there, but to keep everything clean it is suggested to save it to another file and import in `userContent.css` like mentioned in the header

then open in `about:config` change value of `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`

sorry for the inconvenience

**Comment by zakius** [comment]
I just uploaded new version supporting custom styles to GH, I'll keep this one open as a reference

**Comment by atomGit** [comment]
thanks zakius :)

**Comment by skosch** [comment]
Not sure where else to share this, but here's a light theme based loosely on Feedbin's styling:

![smartrss](https://user-images.githubusercontent.com/554383/110252407-1578c880-7f3a-11eb-88a3-10aceafdef4d.png)

<details><summary>CSS</summary>

```css
/* MAIN */
html, body {
  font-family: Inter !important;
  background: #fbfaf8;
}

/* LISTS */
#feed-list {
  background: #f7f5f5 !important;
}
.sources-list-item {
  padding: 6px 16px !important;
}
.sources-list-item:hover:not(.selected) .source-title {
  color: inherit !important;
}
.sources-list-item:hover:not(.selected) {
  background: #f0eeed !important;
}

#article-list {
  scrollbar-width: none;
  font-family: Inter !important;
  background: #f7f5f5 !important;
}
#article-list:hover {
  scrollbar-width: auto;
  scrollbar-color: var(--grey-50) #e8e4e1;
}
.articles-list-item {
  padding: 12px 8px !important;
}
.articles-list-item:hover:not(.selected) {
  background: #f0eeed !important;
}
.item-pin:empty {
  background-size: .66rem !important;
}
.item-date {
  flex: 0 1 20px !important;
}
.item-author {
  white-space: normal !important;
}
.item-title {
  white-space: normal !important;
  font-weight: 600 !important;
  color: var(--grey-80) !important;
}
.date-group {
  display: none !important;
}
.region:not(.focused) .selected {
  background: #d9d2cc !important;
  border-bottom-color: var(--grey-30);
}
.selected * {
  color: var(--grey-90) !important;
}
.selected .item-author {
  color: var(--grey-60) !important;
}

/* TOOLBAR */
.toolbar {
  background: #e8e4e1 !important;
}
input[type="search"] {
  max-width: 260px !important;
  width: 260px !important;
  background: rgba(255,255,255,0.5) !important;
  font-size: .6rem;
}

/* ARTICLE HEADER */
header {
  background: #fbfaf8;
  padding: 1rem 3rem !important;
}
header .date {
  flex: 0 1 300px !important;
}

/* ARTICLE BODY */
#content {
  scrollbar-color: var(--grey-50) #e8e4e1;
}
#smart-rss-article-body {
  font-family: CrimsonProS !important;
  max-width: 65ch !important;
  font-size: 22pt;
  padding: 1rem 3rem !important;
  background: #fbfaf8;
}
summary a {
  display: none;
}
a {
  color: #734f35;
}
#smart-rss-content-footer a {
  background-color: #fbfaf8 !important;
}
```
</details>
